### ISSUE TITLE
contact

### ISSUE THREAD

**Issue by rdissertori** [un1versal/revamped.themes#2]
I'd love to contact you about 

```
**<linkremoved to keep private> each time you link it pops up as a reference and which can be used to track cross reference comments** and removing link doesn't work as I expected.
```

but there seems no way to contact you via xbmc/kodi forum (you disabled PM's) nor via github other than through "issues

**Comment by uNiversaI** [comment]
I am in IRC often, please join freenode #kodi #kodi-linux and or kodi forums.

I have all manners of private contact disabled as none should be private in relation to these or other kodi related matters. ... 

More appropriate to actually make a comment in the youtube ticket then to post a ticket unrelated in a totally unrelated project.

Now that you have what would you like to know? Its simple really, the old youtube addon supportd downloading clips from youtube to local, the new one doesn't and I would like it to support it. There is nothing else special about this that I am aware.

What would you like to know?

Im closing this ticket but fee free to reply I will still be able to read it and respond.

**Comment by rdissertori** [comment]
Thanks first of all my intend is to help you in your downloading issue, I wanted it to keep it in private for reason below:

I'm an addon dev myself, and I wanted to contribute to this addon-rework (old authors seemed to have retired) by is now done by "bromix".
Unfortunately it's not easy to contact him in private aswell hence I ended up posting it as "issue" aswell.
You will find the conversation at https://github.com/bromix/plugin.video.youtube/issues/140
which is not really constructive (rather rude) but informative:
You will find out yourself following the url he posted. It's unlikely he will be implementing such feature. 

And thats where I jump in - I see no logical reason why not implementing this feature that you suggested there. In fact I've fully implemented single and multiple downloads within the context menu without touching any of bromix'es code.

you can find the sourcecode on https://github.com/rdissertori/xbmc-addons/tree/master/repository.moo.kodi.addons.repository

I'm just posting this because I thought it would be nice to share
cheers _moo_

**Comment by uNiversaI** [comment]
Yes... I saw your repo once you msg me.

Im not a fan of using 20 addons for job of one. why dont you submit the code changes to bromix? then if its not implemented he can close the ticket he opened himself.

The guy strikes me as rude and abrasive, but some people are naturally like this, not everyone can handle human interaction well.

I disagree that download is not a feature but there are many valid reason to have it, mine is Im often without access to online content and such are planed I grab content of interest via yourtube addon.

That said, I suggest that you can provide a patch which I will help test so thers no issues cause therefore he have no choice but to either implement or not.

Youtube is the only addon I use.

**Comment by uNiversaI** [comment]
What I suggest is you fork his youtube current addon and add your changes, I will test it to death and then you can try submit it as PR see what happens.

if it works great Im interested in this. I would hate to have to use firefox addons to do this but such will be the course when old addon stops working.

maybe you can submit your addon to the main repo there is also nothing stopping you from doing this. Call it youtubed for e.g. I can help you with icon/fanart.

**Comment by rdissertori** [comment]
Thanks a lot, for those suggestions (and privacy changes). I've already forked the project by now and will merge my changes into it. Since I've implemented it modular and independant from his code all the changes from his side won't overwrite any changes of mine.

I think so too that the kodi devs are acting unreasonable in this matter - that's why I just took matters into my own hands.

I'm using the downloading features already on daily basis and I don't see why I should not share it with anyone. You can already test it by downloading my repository (just install the repository zip) on
https://github.com/rdissertori/xbmc-addons/raw/master/repository.moo.kodi.addons.repository/repository.moo.kodi.addons.repository-1.0.5.zip
so you will automatically get updates on this.

I'm looking forward to comments on this and of course styling it would be more than welcome, because I dislike the icons/fanart aswell. Just mind don't the name "Moo Youtube" i was not very creative in this matter - so I will adjust it to whatever anyone suggests.
Just as a sidenote you will find the settings for the download folder in the "Moo" Tab of the addon settings.
